name: Deploy Armada Infra to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

    - name: Bicep Deploy
      uses: Azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        name: ${{ github.run_id }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        resource-group-name: rg-armada
        template-file: ./bicep/novnet/main.bicep
        parameters-file: ./bicep/novnet/main.bicepparam
        parameters: '{"prefix":"armada"}'
