name: Deploy Armada Infra to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

    - name: Bicep Deploy
      uses: Azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        name: ${{ github.run_id }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        resource-group-name: rg-armada
        template-file: ./bicep/novnet/main.bicep
        parameters: |
          '{
            "prefix":"armada", 
            "suffix":"0001", 
            "userObjectId":"1c408c2b-3b76-46c0-861c-aa82bd370036",
            "keyVaultEnableSoftDelete":false,
            "keyVaultEnablePurgeProtection":false,
            "hubFriendlyName":"Armada Hub",
            "hubDescription":"Armada Hub",
            "projectFriendlyName":"Armada Project",
          }'
